config/routes.rb
Rails.application.routes.draw do
  resources :collaborators
  resources :wikis
  devise_for :users
  get 'about' => 'welcome#about'
  resources :charges, only: [:new, :create]
  get 'charges/downgrade' => 'charges#downgrade', :as => :downgrade
  # get 'collaborators/add_collaborator' => 'collaborator#add_collaborator', :as => :add_collaborator
  root 'welcome#index'  
end

app/models/amount.rb
class Amount < ActiveRecord::Base
    def self.default
        1000
    end
end

app/models/charge.rb
class Charge < ActiveRecord::Base

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
    belongs_to :wiki
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :wikis
  has_many :collaborators
  
  enum role: [:standard, :premium, :admin]
  
  after_initialize :set_role_to_standard
  
  def set_role_to_standard
    self.role ||= "standard"
  end
  
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  
  validates :user, presence: true
  validates :body, length: {minimum: 20}, presence: true
  validates :title, length: {minimum: 5}, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :authenticate_user!, only: [:index, :show] 
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    
    def create
        # Creates a Stripe Customer object, for associating
        # with the charge
        customer = Stripe::Customer.create(
            email: current_user.email,
            card: params[:stripeToken]
        )
     
        # Where the real magic happens
        charge = Stripe::Charge.create(
            customer: customer.id, # Note -- this is NOT the user_id in your app
            amount: Amount.default,
            description: "BigMoney Membership - #{current_user.email}",
            currency: 'usd'
        )
        
        current_user.premium!
     
        flash[:notice] = "Thanks, #{current_user.email}! Your account now has a premium subscription."
        redirect_to root_path # or wherever
     
        # Stripe will send back CardErrors, with friendly messages
        # when something goes wrong.
        # This `rescue block` catches and displays those errors.
        rescue Stripe::CardError => e
            flash[:alert] = e.message
            redirect_to new_charge_path
            

    end
    
    def new
        @stripe_btn_data = {
            key: "#{ Rails.configuration.stripe[:publishable_key] }",
            description: "BigMoney Membership - #{current_user.email}",
            amount: Amount.default
        }
    end
    
    def downgrade
        if current_user.standard!
            current_user.wikis.update_all(private: false)
            flash[:notice] = "Your account was downgraded successfully."
            redirect_to root_path
        end
    end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_collaborator, only: [:show, :edit, :update, :destroy]

  # GET /collaborators
  def index
    @collaborators = Collaborator.all
  end

  # GET /collaborators/1
  def show
  end

  # GET /collaborators/new
  def new
    @collaborator = Collaborator.new
    @users = User.all
  end

  # GET /collaborators/1/edit
  def edit
  end

  # POST /collaborators
  def create
    @collaborator = Collaborator.new(collaborator_params)

    if @collaborator.save
      redirect_to wikis_path, notice: 'Collaborator was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /collaborators/1
  def update
    if @collaborator.update(collaborator_params)
      redirect_to @collaborator, notice: 'Collaborator was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /collaborators/1
  def destroy
    @collaborator.destroy
    redirect_to wikis_path, notice: 'Collaborator was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collaborator
      @collaborator = Collaborator.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def collaborator_params
      params.require(:collaborator).permit(:user_id, :wiki_id)
    end
    
    # def add_collaborator(user)
    #     @wiki = Wiki.find(params[:id])
    #     @users = User.all
    #     if @users.include?(user)
    #         if Collaborator.create(user_id: user.id)
    #             flash[:notice] = "Successfully added #{user.email} as a collaborator to #{@wiki.title}."
    #             redirect_to root_path
    #         end
    #     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #before_action :authenticate_user!
    #(use in other controllers, such as posts/topics)
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
    before_action :user_check, only: [:edit, :update, :new, :create, :destroy]
    
    def index
       @wikis = policy_scope(Wiki)
    end
    
    def show
        @wiki = Wiki.find(params[:id])
        @collaborators = Collaborator.where(wiki_id: @wiki.id)
    end
    
    def new
        @wiki = Wiki.new
    end
    
    def create
        @wiki = Wiki.new(wiki_params)
        @wiki.user = current_user
        
        if @wiki.save
           flash[:notice] = "Wiki was saved."
           redirect_to @wiki
        else
            flash.now[:alert] = "There was an error saving the wiki. Please try again."
            render :new
        end
    end
    
    def edit
        @wiki = Wiki.find(params[:id])
    end
    
    def update
        @wiki = Wiki.find(params[:id])
        @wiki.assign_attributes(wiki_params)
        
        if @wiki.save
            flash[:notice] = "Wiki was updated."
            redirect_to @wiki
        else
            flash.now[:alert] = "There was an error saving the wiki. Please try again."
            render :edit
        end
    end
    
    def destroy
        @wiki = Wiki.find(params[:id])
     
        if @wiki.destroy
          flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
          redirect_to action: :index
        else
          flash.now[:alert] = "There was an error deleting the wiki."
          render :show
        end
    end
    
    private
    def wiki_params
        params.require(:wiki).permit(:title, :body, :private)
    end
    
    def user_check
        unless user_signed_in?
            flash[:notice] = "You must be logged in to do that."
            redirect_to wikis_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
    
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/_form.html.erb
<%= form_tag charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/charges/edit.html.erb
<h1>Editing Charge</h1>

<%= render 'form' %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Charges</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charges.each do |charge| %>
      <tr>
        <td><%= link_to 'Show', charge %></td>
        <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charge', new_charge_path %>

app/views/charges/new.html.erb
<h1>Upgrade to Premium</h1>

<%= render 'form' %>

<%= link_to 'Back', charges_path %>

app/views/charges/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_charge_path(@charge) %> |
<%= link_to 'Back', charges_path %>

app/views/collaborators/_form.html.erb
<%= form_for(@collaborator) do |f| %>

  <% if @collaborator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collaborator.errors.count, "error") %> prohibited this collaborator from being saved:</h2>
      <ul>
      <% @collaborator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
      <table>
        <tbody>
            <%= f.collection_select :user_id, User.where.not(id: current_user.id), :id, :email %>
        </tbody>
    </table>
  <%= f.hidden_field :wiki_id, :value => params[:wiki_id] %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collaborators/edit.html.erb
<h1>Editing Collaborator</h1>

<%= render 'form' %>

<%= link_to 'Show', @collaborator %> |
<%= link_to 'Back', collaborators_path %>

app/views/collaborators/index.html.erb
<p id="notice"><%= notice %></p>
<% wiki = Wiki.find(params[:wiki]) %>
<h1><%= "#{wiki.title} Collaborators" %></h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% wiki.collaborators.each do |collaborator| %>
      <tr>
        <td><%= "#{User.find(collaborator.user_id).email}" %></td>
        <td><%= link_to 'Destroy', collaborator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to "Add collaborator", { :controller => "collaborators", :action => "new", :wiki_id => wiki.id } %>

app/views/collaborators/new.html.erb
<h1>New Collaborator</h1>
    
<%= render 'form' %>

<%= link_to 'Back', wikis_path %>

app/views/collaborators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @collaborator.user_id %>
</p>

<%= link_to 'Edit', edit_collaborator_path(@collaborator) %> |
<%= link_to 'Back', collaborators_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
  <div class="user-bar">
    <div class="pull-left">
      <%= link_to "Home", root_path, class: "home-link" %>
    </div>
    <div class="pull-right">
      <% if user_signed_in? %>
        Signed in as: <strong><%= current_user.email %></strong> 
        <% if current_user.role == "standard" %>
          <%= "- #{current_user.role.capitalize} account" %> - <%= link_to "Upgrade", new_charge_path, :class => 'navbar-link'  %>
        <% elsif current_user.role == "premium" %>
          <%= "- #{current_user.role.capitalize} account" %> - <%= link_to "Downgrade", downgrade_path, :class => 'navbar-link', data: { confirm: 'Are you sure you want to downgrade your account?' }  %>
        <% end %>
        |
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
  </div>

  
  <%= yield %>
  
  </body>
</html>

app/views/welcome/index.html.erb
<div class="center-block wikilist">
    <% if user_signed_in? %>
        <% @all_wikis = Wiki.where(user_id: current_user.id) %>
    <% else %>
        <% @all_wikis = Wiki.all %>
    <% end %>
    <% if user_signed_in? %>
        <h2>My wikis</h2>
    <% else %>
        <h2>All wikis</h2>
    <% end %>
        <% @all_wikis.each do |wiki| %>
            <% unless (user_signed_in? && current_user.id != wiki.user_id && wiki.private) || (!user_signed_in? && wiki.private) %>
                    <div class="row">
                        <% if user_signed_in? %>
                            <div class="col-sm-9">
                        <% else %>
                            <div class="col-sm-12">
                        <% end %>
                            <%= link_to wiki.title, wiki %></div>
                        <% if user_signed_in? %>
                            <div class="col-sm-1"><%= link_to "Edit", edit_wiki_path(wiki) %></div>
                            <div class="col-sm-2"><%= link_to 'Destroy', wiki, method: :delete, data: { confirm: 'Are you sure?' } %></div>
                        <% end %>
                    </div>
                <% #end %>
            <% end %>
        <% end %>
    <% if current_user %>
        <div class="center-block" style="text-align: center; margin-top: 15px;">
            <%= link_to "All wikis", wikis_path, class: "new-wiki" %>&nbsp;&nbsp;
            <%= link_to "New wiki", new_wiki_path, class: "new-wiki" %>
        </div>
    <% end %>
</div>

app/views/wikis/_form.html.erb
<%= form_for(@wiki) do |f| %>
  <% if @wiki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wiki.errors.count, "error") %> prohibited this wiki from being saved:</h2>
      <ul>
      <% @wiki.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title." %>

  <%= f.label :body %>
  <%= f.text_area :body, class: 'form-control', rows: 8, placehodler: "Enter post body." %>
  <div class="actions">
    
  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %><span class="checkbox-label">Private wiki</span>
      <% end %>
    </div>
  <% end %>
    <%= f.submit %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<div class="wiki-edit">
    <h1>Editing Wiki</h1>
    
    <%= render 'form' %>
    
    
    <% if @wiki.private && @wiki.user_id == current_user.id && current_user.role == 'premium' %>
        <% wiki_id = @wiki.id %>
        <%= link_to "Edit collaborators", {:controller => "collaborators", :action => "index", :wiki => @wiki } %> | 
    <% end %>
    <%= link_to 'Show', @wiki %> |
    <%= link_to 'Back', wikis_path %>
</div>

app/views/wikis/index.html.erb
<div class="wiki-index"><p id="notice"><%= notice %></p>

  <h1>Listing Wikis</h1>
  
  <table>
    <tbody>
      <% @wikis.each do |wiki| %>
  
          <tr>
            <td><h2><%= wiki.title %></h2></td>
          </tr>
          <tr>
            <td><p><%= wiki.body %></p></td>
          </tr>
          <tr>
            <% if current_user && (current_user.id == wiki.user_id || wiki.users.include?(current_user.id)) %>
              <td><%= link_to 'Edit', edit_wiki_path(wiki) %></td>
              <td><%= link_to 'Destroy', wiki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/wikis/new.html.erb
<div class="wiki-new">
    <h1>New Wiki</h1>
    
    <%= render 'form' %>
    
    <%= link_to 'Back', wikis_path %>
</div>

app/views/wikis/show.html.erb
<div class="wiki-show">
    <p id="notice"><%= notice %></p>
    
    <h2><%= @wiki.title %></h2>
    <p><%= markdown(@wiki.body) %></p>
    
    <% if @wiki.private && @wiki.user_id == current_user.id && current_user.role == 'premium' %>
        <% wiki_id = @wiki.id %>
        <%= link_to "Edit collaborators", collaborators_path %> | 
    <% end %>
    <% unless current_user.nil? %>
        <% if @collaborators.include?(current_user.id) || @wiki.user_id == current_user.id %>
            <%= link_to 'Edit', edit_wiki_path(@wiki) %> |
        <% end %>
    <% end %>
    <%= link_to 'Back', wikis_path %>
</div>